apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: news-paper-demo
  template:
    metadata:
      labels:
        app: news-paper-demo
    spec:
      containers:
      - name: my-springboot-app
        image: public.ecr.aws/b1q3n2s0/jenkins-eks
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
        command: ["/bin/sh"]
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-paper-demo
    k8s-app: news-paper-demo
  name: news-paper-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: news-paper-demo
